log:
  level: DEBUG

api:
  insecure: true
  dashboard: false

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: :5173

accessLog: {}
