apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wordle-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: wordle-http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: user
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
spec:
  hosts:
  - "*"
  gateways:
  - wordle-gateway
  http:
  - match:
    - uri:
        prefix: /user
    route:
    - destination:
        host: user
        port:
          number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-v1
  labels:
    app: user
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      containers:
      - name: user
        image: user-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: score
  labels:
    app: score
    service: score
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: score
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: score
spec:
  hosts:
  - "*"
  gateways:
  - wordle-gateway
  http:
  - match:
    - uri:
        prefix: /score
    route:
    - destination:
        host: score
        port:
          number: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-v1
  labels:
    app: score
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score
      version: v1
  template:
    metadata:
      labels:
        app: score
        version: v1
    spec:
      containers:
      - name: score
        image: score-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: ranking
  labels:
    app: ranking
    service: ranking
spec:
  ports:
  - port: 3002
    name: http
  selector:
    app: ranking
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ranking
spec:
  hosts:
  - "*"
  gateways:
  - wordle-gateway
  http:
  - match:
    - uri:
        prefix: /ranking
    route:
    - destination:
        host: ranking
        port:
          number: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-v1
  labels:
    app: ranking
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranking
      version: v1
  template:
    metadata:
      labels:
        app: ranking
        version: v1
    spec:
      containers:
      - name: rank
        image: rank-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
        env:
          - name: userServer
            value: "user"
          - name: scoreServer
            value: "score"
---
apiVersion: v1
kind: Service
metadata:
  name: wordle-frontend
  labels:
    app: wordle-frontend
    service: wordle-frontend
spec:
  ports:
  - port: 5173
    name: http
  selector:
    app: wordle-frontend
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wordle-frontend
spec:
  hosts:
  - "*"
  gateways:
  - wordle-gateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /sverdle
    - uri:
        prefix: /rank
    route:
    - destination:
        host: wordle-frontend
        port:
          number: 5173
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-frontend-v1
  labels:
    app: wordle-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordle-frontend
      version: v1
  template:
    metadata:
      labels:
        app: wordle-frontend
        version: v1
    spec:
      containers:
      - name: wordle
        image: wordle-web
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
        env:
          - name: PORT
            value: "5173"
